-- Set nama_produk=kode sediaan, kandungan, nama_dagang (merk asli internal)
-- Jalankan SETELAH migrasi 20260918_0100 (kolom kandungan/nama_dagang ada).
USE db_sehati;

UPDATE master_produk SET nama_produk='Cream CP', kandungan='Clobetasol Propionat 0,05%', nama_dagang='Forderm Cream' WHERE kode_produk='TPK-001';
UPDATE master_produk SET nama_produk='CP Oint', kandungan='Clobetasol Propionat 0,05%', nama_dagang='Ikaderm Oint' WHERE kode_produk='TPK-002';
UPDATE master_produk SET nama_produk='Cream MO', kandungan='Mometasone furoate 0,1%', nama_dagang='Dermovel Cream' WHERE kode_produk='TPK-003';
UPDATE master_produk SET nama_produk='MO Oint', kandungan='Mometasone furoate 0,1%', nama_dagang='Momero Oint' WHERE kode_produk='TPK-004';
UPDATE master_produk SET nama_produk='Cream B', kandungan='Betamethasone Valerate 0,1%', nama_dagang='Benoson Cream' WHERE kode_produk='TPK-005';
UPDATE master_produk SET nama_produk='Cream D', kandungan='Desonide 0,05%', nama_dagang='Dermades Cream' WHERE kode_produk='TPK-006';
UPDATE master_produk SET nama_produk='Des Cream', kandungan='Desoximethasone 0,25%', nama_dagang='Desoxiron Cream' WHERE kode_produk='TPK-007';
UPDATE master_produk SET nama_produk='Des Oint', kandungan='Desoximethasone 0,25%', nama_dagang='Inerson Oint' WHERE kode_produk='TPK-008';
UPDATE master_produk SET nama_produk='CP Lotion', kandungan='Clobetasol Propionat 0,05%', nama_dagang='Kloderma Lotion' WHERE kode_produk='TPK-009';
UPDATE master_produk SET nama_produk='AB Cream', kandungan='Mupirocin Calcium 2%', nama_dagang='Bactoderm Cream' WHERE kode_produk='TPK-010';
UPDATE master_produk SET nama_produk='AB Oint', kandungan='Mupirocin Calcium 2%', nama_dagang='Bactoderm Oint' WHERE kode_produk='TPK-011';
UPDATE master_produk SET nama_produk='Cream C', kandungan='Clindamycin Phospate 10 mg/gr', nama_dagang='Clindion Cream' WHERE kode_produk='TPK-012';
UPDATE master_produk SET nama_produk='Cream E', kandungan='Erythromycin 2%', nama_dagang='Erymed Cream' WHERE kode_produk='TPK-013';
UPDATE master_produk SET nama_produk='AB 2 Cream', kandungan='Gentamycin Sulfate 0,1 %', nama_dagang='Ikagen Cream' WHERE kode_produk='TPK-014';
UPDATE master_produk SET nama_produk='AB 2 Oint', kandungan='Gentamycin Sulfate 0,1 %', nama_dagang='Ikagen Oint' WHERE kode_produk='TPK-015';
UPDATE master_produk SET nama_produk='FD Cream', kandungan='Fusidic acid 2%', nama_dagang='Fusipar Cream' WHERE kode_produk='TPK-016';
UPDATE master_produk SET nama_produk='FD Oint', kandungan='Sodium Fusidate 2%', nama_dagang='Fusipar Oint' WHERE kode_produk='TPK-017';
UPDATE master_produk SET nama_produk='Prodiva Gel', kandungan='Lactobacillus Ferment', nama_dagang='Prodiva Gel' WHERE kode_produk='TPK-018';
UPDATE master_produk SET nama_produk='Cream BP', kandungan='HA, Silver Sulfadiazine', nama_dagang='Burnazin Plus' WHERE kode_produk='TPK-019';
UPDATE master_produk SET nama_produk='Acnedine Cream', kandungan='Nadifloxacine', nama_dagang='Acnedine Cream' WHERE kode_produk='TPK-020';
UPDATE master_produk SET nama_produk='Cream Kutu', kandungan='Permethrin 5%', nama_dagang='Scabicore Cream' WHERE kode_produk='TPK-021';
UPDATE master_produk SET nama_produk='Zoter Cream', kandungan='Aciclovir 5%', nama_dagang='Zoter Cream' WHERE kode_produk='TPK-022';
UPDATE master_produk SET nama_produk='Papilocare', kandungan='Tea Tree, Lavender Extrak, Chamomile, Asam Glikolat', nama_dagang='Papilocare' WHERE kode_produk='TPK-023';
UPDATE master_produk SET nama_produk='Cream K', kandungan='Ketokonazole 2%', nama_dagang='Fungasol Cream' WHERE kode_produk='TPK-024';
UPDATE master_produk SET nama_produk='Fungares', kandungan='Miconazole Nitrat 2%', nama_dagang='Fungares Cream' WHERE kode_produk='TPK-025';
UPDATE master_produk SET nama_produk='Termisil cream', kandungan='Terbinafine HCl 1%', nama_dagang='Termisil Cream' WHERE kode_produk='TPK-026';
UPDATE master_produk SET nama_produk='Lotion K', kandungan='ketokonazole 2%', nama_dagang='Erazol Lotion' WHERE kode_produk='TPK-027';
UPDATE master_produk SET nama_produk='Cream DP', kandungan='Astaxanthin, Niacinamide, Vit C, Vit B5', nama_dagang='Dermapro Cream' WHERE kode_produk='TPK-028';
UPDATE master_produk SET nama_produk='Effagel gel (AD Gel)', kandungan='Adapalene 0,1%', nama_dagang='Effagel Gel' WHERE kode_produk='TPK-029';
UPDATE master_produk SET nama_produk='Evalen gel (AD Gel)', kandungan='Adapalene 0,1%', nama_dagang='Evalen Gel' WHERE kode_produk='TPK-030';
UPDATE master_produk SET nama_produk='AD Cream', kandungan='Adapalene 0,1%', nama_dagang='Evalen Cream' WHERE kode_produk='TPK-031';
UPDATE master_produk SET nama_produk='Cream Pagi/AH', kandungan='Glycolic acid 10 %', nama_dagang='Glycore Cream' WHERE kode_produk='TPK-032';
UPDATE master_produk SET nama_produk='Gel N2', kandungan='Niacinamide 4%, Tranex peptides, Sodium Hyaluronate', nama_dagang='Niaclear Gel' WHERE kode_produk='TPK-033';
UPDATE master_produk SET nama_produk='Cream H', kandungan='Hydroquinon 5%', nama_dagang='Equinon Forte' WHERE kode_produk='TPK-034';
UPDATE master_produk SET nama_produk='W3', kandungan='Hydroquinon 4%, Tretinoin 0,05%, Fluocinolon acetonide 0,01%', nama_dagang='Refaquin Cream' WHERE kode_produk='TPK-035';
UPDATE master_produk SET nama_produk='Fut krim', kandungan='Extract cactus 2%, Urea', nama_dagang='Futkrim' WHERE kode_produk='TPK-036';
UPDATE master_produk SET nama_produk='Repair Cream', kandungan='Panthenol 5%, Extract Centella Asiatica', nama_dagang='Cicaplast gel B5' WHERE kode_produk='TPK-037';
UPDATE master_produk SET nama_produk='Baume 1', kandungan='Panthenol 5%, Tribioma madecassoside, Copper, Zinc, Manganese', nama_dagang='Cicaplast Baume B5' WHERE kode_produk='TPK-038';
UPDATE master_produk SET nama_produk='Soothing Baume 2', kandungan='Centella Asiatica', nama_dagang='Soothing Baume 2' WHERE kode_produk='TPK-039';
UPDATE master_produk SET nama_produk='Skin Comforting Cream', kandungan='Ceramide, Panthenol, Shea Butter', nama_dagang='Skin Comforting Cream' WHERE kode_produk='TPK-040';
UPDATE master_produk SET nama_produk='Toner Normal', kandungan='Chamomile extract, Aloe vera, Witch Hazel Extract', nama_dagang='Toner Chamomile' WHERE kode_produk='TPK-041';
UPDATE master_produk SET nama_produk='Lotion NO', kandungan='Ceramide, Cholestrol, Free fatty asid', nama_dagang='Ceradan Daily Moisturising Cream' WHERE kode_produk='TPK-042';
UPDATE master_produk SET nama_produk='Cream A', kandungan='Alpha arbutin, Kojic dipalmitate, Vit C, Niacinamdie', nama_dagang='Arbu-C Cream' WHERE kode_produk='TPK-043';
UPDATE master_produk SET nama_produk='Lotion AH 15', kandungan='AHA 15%, Dimethicone, Phenoxyethanol', nama_dagang='AH Smoothing Lotion' WHERE kode_produk='TPK-044';
UPDATE master_produk SET nama_produk='Gel N3', kandungan='Nicotinamide 4%', nama_dagang='Niaderm' WHERE kode_produk='TPK-045';
UPDATE master_produk SET nama_produk='Cream UA', kandungan='Urea', nama_dagang='Carmed 20%' WHERE kode_produk='TPK-046';
UPDATE master_produk SET nama_produk='Lotion Rambut M', kandungan='Minoxidil 5%', nama_dagang='Proxidil 5%' WHERE kode_produk='TPK-047';
UPDATE master_produk SET nama_produk='Remscar Gel', kandungan='Silicone Gel, Vegetable squalen, Vit E', nama_dagang='Remscar Gel' WHERE kode_produk='TPK-048';
UPDATE master_produk SET nama_produk='Cream KP', kandungan='Ceramide, Urea, Salicilic acid, LHA', nama_dagang='Cerave Smoothing Cream' WHERE kode_produk='TPK-049';
UPDATE master_produk SET nama_produk='Serum Radiant', kandungan='Peptide Formula, Croton Lechleri Resin Extract', nama_dagang='Serum Radiant' WHERE kode_produk='TPK-050';
UPDATE master_produk SET nama_produk='Serum Acne', kandungan='Green Tea Extract, Glactomyces Ferment Filtrat, Willow Bark Extract', nama_dagang='Serum Acne' WHERE kode_produk='TPK-051';
UPDATE master_produk SET nama_produk='Lotion SPF', kandungan='Lactic Acid, Morus Alba Root Extract', nama_dagang='Whitening Body Lotion' WHERE kode_produk='TPK-052';
UPDATE master_produk SET nama_produk='KP Body Spray', kandungan='Salisilic acid, Zinc, Prebiotik, Pomello Extract', nama_dagang='Alfacid Body Spray' WHERE kode_produk='TPK-053';
UPDATE master_produk SET nama_produk='Fresh Out Cream (Sweat Cream)', kandungan='Aluminium chlorohydrate', nama_dagang='Fresh Out Cream (Sweat Cream)' WHERE kode_produk='TPK-054';
UPDATE master_produk SET nama_produk='AD/Cooling Gel', kandungan='Hydroxyphenyl Propamidobenzoic Acid, Mentyl Lactate, Ceramide', nama_dagang='AD Pro Soothing Gel' WHERE kode_produk='TPK-055';
UPDATE master_produk SET nama_produk='Moist Gel', kandungan='Squalene, Vit E, Aloe Vera', nama_dagang='AcMist' WHERE kode_produk='TPK-056';
UPDATE master_produk SET nama_produk='UV Gel', kandungan='Zinc Oxide 3%, Titanium Oxide 1%, Etilhexyl methoxycinamate 9,50 %', nama_dagang='UV Doux' WHERE kode_produk='TPK-057';
UPDATE master_produk SET nama_produk='SB Ungu/Normal', kandungan='Titanium dioxide, Methyl eter dimetil silane, Tinoxide, Hyaluronic Acid', nama_dagang='SB Ungu/Normal' WHERE kode_produk='TPK-058';
UPDATE master_produk SET nama_produk='SB Acne/Hijau', kandungan='Titanium dioxide, Trietil hexanoin, TEA, Hyaluronic Acid', nama_dagang='SB Acne/Hijau' WHERE kode_produk='TPK-059';
UPDATE master_produk SET nama_produk='SB Sensitive/Coklat', kandungan='Trietil hexanoin, Zinc Oxide, Titanium dioxide, Hyaluronic Acid', nama_dagang='SB Sensitive/Coklat' WHERE kode_produk='TPK-060';
UPDATE master_produk SET nama_produk='SB 30A', kandungan='Dibutil adipate, Titanium dioxide, Etilhexyl Salisilate, Camelia Sinensis leave extract', nama_dagang='Daily UV Protection Cream SPF 30' WHERE kode_produk='TPK-061';
UPDATE master_produk SET nama_produk='SB 50', kandungan='Beta glucan, cation HA, Carnosine', nama_dagang='SB 50' WHERE kode_produk='TPK-062';
UPDATE master_produk SET nama_produk='SPF SENSITIVE', kandungan='Octyl methoxycinnamate', nama_dagang='SPF SENSITIVE UFI' WHERE kode_produk='TPK-063';
UPDATE master_produk SET nama_produk='Advance Cream', kandungan='Lactobionic acid, Ceramide', nama_dagang='Ceradan Advance Cream' WHERE kode_produk='TPK-064';
UPDATE master_produk SET nama_produk='Cream DC', kandungan='Ceramide, zinc oxide, octenide', nama_dagang='Ceradan Diaper Cream' WHERE kode_produk='TPK-065';
UPDATE master_produk SET nama_produk='Serum DS 1', kandungan='Clobetasol Propionate 0,05%, Ketokonazole 2%', nama_dagang='Serum DS 1' WHERE kode_produk='TPK-066';
UPDATE master_produk SET nama_produk='Cream Hydra', kandungan='Ceramides, Allantoin, Enoxolone', nama_dagang='Sebium Hydra cream' WHERE kode_produk='TPK-067';
UPDATE master_produk SET nama_produk='Lotion Rambut Malam', kandungan='Proxidil 5%, Skinovit (Tretinoin 0,1%)', nama_dagang='Lotion Rambut Malam' WHERE kode_produk='TPK-068';
UPDATE master_produk SET nama_produk='Cream PW', kandungan='Kojic Acid, N-Butyl Resorcinol, Niacinamide, Tetrahydrocurcumin, Vitamin F', nama_dagang='Pynocare Cream' WHERE kode_produk='TPK-069';
UPDATE master_produk SET nama_produk='Ecta Cream', kandungan='Hesperidin, Glycosaminoglycans, Ectoin, Sodium Hyaluronate, Chrolella Vulgaris Extract', nama_dagang='Ecta Cream' WHERE kode_produk='TPK-070';
UPDATE master_produk SET nama_produk='Serum DS 2', kandungan='Pseudoaltermonas Ferment Extract, Climbazole, Salicylic Acid, Trehalose, Inulin, Poiroctone Olamine', nama_dagang='Hair Tonic UFI' WHERE kode_produk='TPK-071';
UPDATE master_produk SET nama_produk='Gentle Wash', kandungan='Ceramide, Cholestrol, Fatty Acid', nama_dagang='Ceradan Gentle Cleanser' WHERE kode_produk='TPK-072';
UPDATE master_produk SET nama_produk='Acne Wash', kandungan='Salisilic acid, Tea Tree', nama_dagang='Tea Tree Face Wash' WHERE kode_produk='TPK-073';
UPDATE master_produk SET nama_produk='Oily Wash', kandungan='Sodium PCA, Salisilic acid', nama_dagang='Oily Skin Wash' WHERE kode_produk='TPK-074';
UPDATE master_produk SET nama_produk='Soft Wash', kandungan='Gluconolactone, Betaine', nama_dagang='Hydrating Soft Wash' WHERE kode_produk='TPK-075';
UPDATE master_produk SET nama_produk='Ad Wash', kandungan='Cetearyl olivate, Ceramide, Sorbitan olivate', nama_dagang='AD Pro Body Wash' WHERE kode_produk='TPK-076';
UPDATE master_produk SET nama_produk='KP Wash', kandungan='Ceramide, salislic acid, hyaluronic acid', nama_dagang='Cerave SA Cleanser' WHERE kode_produk='TPK-077';
UPDATE master_produk SET nama_produk='Milk Cleanser', kandungan='Glycerin, Dimethicone', nama_dagang='Soft & Refreshing Cleanser' WHERE kode_produk='TPK-078';
UPDATE master_produk SET nama_produk='Shampo DS', kandungan='Cocamidopropyl Betaine, Sodium C14-16 Olefin Sulfonate', nama_dagang='Shampo DS' WHERE kode_produk='TPK-079';
UPDATE master_produk SET nama_produk='Shampo Bio', kandungan='Biocomplex B11', nama_dagang='Shampo Bioxine' WHERE kode_produk='TPK-080';

SELECT COUNT(*) updated FROM master_produk WHERE kode_produk LIKE 'TPK-%' AND nama_dagang IS NOT NULL;
SELECT kode_produk,nama_produk,nama_dagang,kandungan FROM master_produk WHERE kode_produk LIKE 'TPK-%' ORDER BY id_produk LIMIT 6;
